### ISSUE TITLE
Iniciar el testeo del proyecto

### ISSUE THREAD

**Issue by BCAndreaC** [thatmare/Queen-pattys#50]
Tests que aportan valor:
- Corroborar que la página se renderiza
- Corroborar que la ruta coincida con el componente

Consideraciones:
- React
- TypeScript
- API mockeada

**Comment by thatmare** [comment]
[https://dev.to/saharabanu/unit-tesing-with-jest-in-react-typescript-3anb](Unit testing with Jest in React TypeScript)
[https://jestjs.io/docs/tutorial-react](Testing React with Jest)
